version: "3"
services:
  backend:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"  # Map the port dynamically based on the environment variable
    environment:
      - MONGO_URI=${MONGO_URI}  # Use environment variable from the .env file
      - SECRET_KEY=${SECRET_KEY}  # Load secret key from .env file
      - SERVER_PORT=${SERVER_PORT}  # Use the SERVER_PORT from the .env file
    volumes:
      - uploads:/src/uploads  # Persist the uploads folder
    depends_on:
      - mongo  # Ensure mongo starts before the backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # Expose MongoDB's default port
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

volumes:
  uploads:
  mongo-data:
