version: "3"
services:
  backend:
    image: b3n3dkt/dailydinner_backend:latest
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    volumes:
      - uploads:/src/uploads
      - ~/.aws:/root/.aws
    depends_on:
      - mongo
  frontend:
    image: b3n3dkt/dailydinner_frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  uploads:
  mongo-data:
