name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'VERSION'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Current Version
        id: get_version
        run: |
          if [ -f VERSION ]; then
            VERSION=$(cat VERSION)
          else
            VERSION="0.0.0"
          fi
          echo "Current version: $VERSION"
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Increment Version
        id: increment_version
        run: |
          CURRENT_VERSION=${{ steps.get_version.outputs.current_version }}
          IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "$NEW_VERSION" > VERSION

      - name: Commit New Version
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION
          git commit -m "Bump version to ${{ steps.increment_version.outputs.new_version }}"
          git push
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./src/frontend
          push: true
          platforms: linux/arm64
          tags: |
            b3n3dkt/dailydinner_frontend:latest
            b3n3dkt/dailydinner_frontend:${{ steps.increment_version.outputs.new_version }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./src/backend
          push: true
          platforms: linux/arm64
          tags: |
            b3n3dkt/dailydinner_backend:latest
            b3n3dkt/dailydinner_backend:${{ steps.increment_version.outputs.new_version }}

      - name: Create Git Tag
        if: github.ref == 'refs/heads/main'
        run: |
          git tag -a "v${{ steps.increment_version.outputs.new_version }}" -m "Version ${{ steps.increment_version.outputs.new_version }}"
          git push origin "v${{ steps.increment_version.outputs.new_version }}"
